direction: right

NIC VM 1: {
    style: {
        stroke: black
        font-color: "#004E5A"
        fill: "#F8EC17"
        opacity: 0.8
      }
}

NIC VM 2: {
    style: {
        stroke: black
        font-color: "#004E5A"
        fill: "#F8EC17"
        opacity: 0.8
      }
}

NIC VM 1 -- NIC VM 2: VRRP HA Sync
