name: "Default CI"

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  secret-scan:
    name: "Secret Scanner (TruffleHog)"
    runs-on: ${{ github.server_url == 'https://github.com' && 'ubuntu-latest' || 'stackit-docker' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: TruffleHog Scan
        uses: edplato/trufflehog-actions-scan@master

  pre-commit-checks:
    name: "Pre-Commit Hooks"
    runs-on: ${{ github.server_url == 'https://github.com' && 'ubuntu-latest' || 'stackit-ubuntu-22' }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v4

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: "1.26"

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "20"

      - name: Install addlicense
        # Installs the tool and adds it to the GitHub Actions PATH so pre-commit can find it
        run: |
          go install github.com/google/addlicense@latest
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1
